# Generated by Django 5.2.8 on 2026-06-13 19:29

from django.db import migrations, models


def populate_languages(apps, schema_editor):
    Language = apps.get_model("user", "Language")
    languages = [
        {
            "name": "CPP",
            "display_name": "C++",
            "judge0_language_id": 54,
            "import_block": (
                "#include <iostream>\n"
                "#include <vector>\n"
                "#include <string>\n"
                "#include <algorithm>\n"
                "#include <map>\n"
                "#include <set>\n"
                "#include <queue>\n"
                "#include <stack>\n"
                "#include <cmath>\n\n"
                "using namespace std;\n"
            ),
        },
        {
            "name": "JAVA",
            "display_name": "Java",
            "judge0_language_id": 62,
            "import_block": "import java.util.*;\nimport java.io.*;\n",
        },
        {
            "name": "PYTHON",
            "display_name": "Python",
            "judge0_language_id": 71,
            "import_block": "import sys\nimport json\nfrom typing import List, Dict, Tuple, Optional\n",
        },
        {
            "name": "JAVASCRIPT",
            "display_name": "JavaScript",
            "judge0_language_id": 63,
            "import_block": "const readline = require('readline');\n",
        },
        {
            "name": "TYPESCRIPT",
            "display_name": "TypeScript",
            "judge0_language_id": 74,
            "import_block": (
                "declare const process: any;\n"
                'declare module "readline";\n'
                "import * as readline from 'readline';\n"
            ),
        },
    ]
    for lang in languages:
        Language.objects.get_or_create(
            name=lang["name"],
            defaults={
                "display_name": lang["display_name"],
                "judge0_language_id": lang["judge0_language_id"],
                "import_block": lang["import_block"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Language code/key (e.g. CPP, JAVA, PYTHON, JAVASCRIPT, TYPESCRIPT)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human readable name of the language (e.g. C++, Java, Python, JavaScript, TypeScript)",
                        max_length=100,
                    ),
                ),
                (
                    "import_block",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Standard imports for this language (common for all problems)",
                    ),
                ),
                (
                    "judge0_language_id",
                    models.IntegerField(
                        help_text="Judge0 language ID corresponding to this language"
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "language",
            },
        ),
        migrations.RunPython(populate_languages),
    ]
