# Generated by Django 5.2.8 on 2026-06-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Human readable name of the language (automatically populated from choices)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                choices=[
                    ("CPP", "C++"),
                    ("JAVA", "Java"),
                    ("PYTHON", "Python"),
                    ("JAVASCRIPT", "JavaScript"),
                    ("TYPESCRIPT", "TypeScript"),
                ],
                help_text="Language code/key (e.g. CPP, JAVA, PYTHON, JAVASCRIPT, TYPESCRIPT)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
