# Generated by Django 5.2.8 on 2026-06-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0012_customtype_remove_testcase_output_type_and_more"),
        ("user", "0004_alter_language_display_name_alter_language_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Language",
        ),
    ]
