# Generated by Django 5.2.8 on 2026-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_discuss_downvotes_discuss_is_editorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_editorial',
            field=models.BooleanField(default=False),
        ),
    ]
