# Generated by Django 5.2.8 on 2026-05-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_solution_is_editorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='is_editorial',
        ),
    ]
