# Generated by Django 5.2.8 on 2026-06-13 19:29

import django.db.models.deletion
from django.db import migrations, models


def migrate_languages(apps, schema_editor):
    Codeblock = apps.get_model("problem", "Codeblock")
    Language = apps.get_model("user", "Language")

    for cb in Codeblock.objects.all():
        try:
            lang_obj = Language.objects.get(name=cb.language_old)
            cb.language = lang_obj
            cb.save()
        except Language.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0010_remove_solution_is_editorial"),
        ("user", "0003_language"),
    ]

    operations = [
        # 1. Drop the unique constraint first so SQLite doesn't complain during column alteration
        migrations.AlterUniqueTogether(
            name="codeblock",
            unique_together=set(),
        ),
        # 2. Remove imports
        migrations.RemoveField(
            model_name="codeblock",
            name="imports",
        ),
        # 3. Rename old language field to language_old
        migrations.RenameField(
            model_name="codeblock",
            old_name="language",
            new_name="language_old",
        ),
        # 4. Add new language ForeignKey field as nullable
        migrations.AddField(
            model_name="codeblock",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codeblocks",
                to="user.language",
                verbose_name="Programming Language",
                null=True,
            ),
        ),
        # 5. Run python script to copy the relationship
        migrations.RunPython(migrate_languages),
        # 6. Remove language_old
        migrations.RemoveField(
            model_name="codeblock",
            name="language_old",
        ),
        # 7. Alter language field to make it non-nullable
        migrations.AlterField(
            model_name="codeblock",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codeblocks",
                to="user.language",
                verbose_name="Programming Language",
            ),
        ),
        # 8. Re-add the unique constraint on the new ForeignKey field
        migrations.AlterUniqueTogether(
            name="codeblock",
            unique_together={("problem", "language")},
        ),
        # 9. Solution.language is converted to CharField without choices
        migrations.AlterField(
            model_name="solution",
            name="language",
            field=models.CharField(
                default="PYTHON", max_length=20, verbose_name="Programming Language"
            ),
        ),
    ]
