# Generated by Django 5.2.8 on 2026-06-17 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0011_remove_codeblock_imports_alter_codeblock_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the custom type (e.g., ListNode)",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Type",
                "verbose_name_plural": "Custom Types",
                "db_table": "custom_type",
            },
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="output_type",
        ),
        migrations.AlterField(
            model_name="codeblock",
            name="language",
            field=models.CharField(
                choices=[
                    ("CPP", "C++"),
                    ("JAVA", "Java"),
                    ("PYTHON", "Python"),
                    ("JAVASCRIPT", "JavaScript"),
                    ("TYPESCRIPT", "TypeScript"),
                ],
                max_length=50,
                verbose_name="Programming Language",
            ),
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the method (e.g., addTwoNumbers)",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Return type of the method", max_length=100
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        blank=True,
                        help_text="Inner type if this is an array",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "array_dimensions",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of dimensions if type is Array"
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="problem.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Method",
                "verbose_name_plural": "Methods",
                "db_table": "method",
            },
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the variable (e.g., nums, target)",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(help_text="Type of the variable", max_length=100),
                ),
                (
                    "template_type",
                    models.CharField(
                        blank=True,
                        help_text="Inner type if this is an array (e.g., Integer for a 1D Array of Integers)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "array_dimensions",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of dimensions if type is Array (e.g., 2 for 2D array)",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Method this variable belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="problem.method",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="problem.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variable",
                "verbose_name_plural": "Variables",
                "db_table": "variable",
            },
        ),
        migrations.CreateModel(
            name="CustomTypeLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("CPP", "C++"),
                            ("JAVA", "Java"),
                            ("PYTHON", "Python"),
                            ("JAVASCRIPT", "JavaScript"),
                            ("TYPESCRIPT", "TypeScript"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "class_declaration",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Class definition (e.g., struct ListNode { ... })",
                    ),
                ),
                (
                    "input_function",
                    models.TextField(
                        blank=True, default="", help_text="Input parsing function"
                    ),
                ),
                (
                    "custom_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="problem.customtype",
                    ),
                ),
            ],
            options={
                "db_table": "custom_type_language",
                "unique_together": {("custom_type", "language")},
            },
        ),
    ]
