# Generated by Django 5.2.8 on 2026-06-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0012_customtype_remove_testcase_output_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="method",
            name="is_constructor",
            field=models.BooleanField(
                default=False, help_text="Is this the constructor method?"
            ),
        ),
    ]
