# Generated by Django 5.2.8 on 2026-06-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0013_method_is_constructor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtypelanguage",
            old_name="input_function",
            new_name="input_output_function",
        ),
        migrations.AlterField(
            model_name="customtypelanguage",
            name="input_output_function",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Input parsing and custom printing function",
            ),
        ),
    ]
