# Generated by Django 5.2.8 on 2026-06-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0014_remove_customtypelanguage_input_function_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="custom_validator",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom Python validator code. Must define 'validate(actual: str, expected: str, tc_input: str) -> bool'",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="validator_type",
            field=models.CharField(
                choices=[
                    ("EXACT", "Exact Match"),
                    ("ANY_ORDER", "Any Order (JSON Array)"),
                    ("CUSTOM", "Custom Validator"),
                ],
                default="EXACT",
                help_text="How to validate the solution output",
                max_length=20,
            ),
        ),
    ]
