# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - api
      - web
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: ./api
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: cdb
      POSTGRES_PORT: 5432
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    init: true
    stdin_open: true
    tty: true
    depends_on:
      - cdb
      - redis
    volumes:
      - ./api:/home/codeflip/api/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  worker:
    container_name: celery_worker
    build:
      context: ./api
    command: celery -A apps worker --loglevel=info
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: cdb
      POSTGRES_PORT: 5432
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    depends_on:
      - cdb
      - redis
    volumes:
      - ./api:/home/codeflip/api/
    networks:
      - app-network

  web:
    container_name: web
    build:
      context: ./web
    environment:
      NODE_ENV: development
    restart: always
    init: true
    stdin_open: true
    tty: true
    command: bun dev
    volumes:
      - ./web:/home/codeflip/web/
      - /home/codeflip/web/node_modules/
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app-network

  cdb:
    image: postgres:16-alpine
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - app-network


volumes:
  pg_data:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
