log_format customformat '$remote_addr - $remote_user [$time_local] '
'"$request" $status $body_bytes_sent '
'"$http_referer"';

server {
    listen 80;
    server_name localhost;
    access_log /dev/stdout customformat;
    client_max_body_size 100M;

    # Backend / API (Nginx passes /api/ as is to Django)
    location /api/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass "http://api:8000/";
        proxy_http_version 1.1;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        send_timeout 300;
        
        # Disable buffering for streaming evaluations and AI generation
        proxy_set_header X-Accel-Buffering no;
    }

    # Static/Media paths (if accessed directly via localhost)
    location /media/ {
        proxy_pass "http://api:8000/media/";
    }
    location /static/ {
        proxy_pass "http://api:8000/static/";
    }

    # Frontend (Default)
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass "http://web:3000";
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
